name: redis
image: docker.io/library/redis:7-alpine
profiles:
  - base
  - service

volumes:
  - name: redis-data
    path: /data
    pool: default
    shifted: true

limits:
  limits.cpu: "1"
  limits.memory: "1GB"

healthcheck:
  path: /
  port: 6379
  timeout: 20
